export default [
	{
		company: 'Capgemini, Mexico City',
		client: '',
		position: 'Team Leader - Senior React Engineer',
		duration: { start: 'February 2022', end: 'Current' },
		technologies: ['React'],
		description: ['I continue to seek the path to greater success :)'],
		roles: ['Manager', 'Team Lead', 'Developer'],
		activities: [],
	},
	{
		company: 'Globant, Mexico City',
		client: 'TaxAct',
		position: 'Web UI Developer',
		duration: { start: 'December 2021', end: 'February 2022' },
		technologies: ['Vue', 'Vuex', 'Contentful'],
		description: [
			"Administration and maintenance of the company's portals.",
		],
		roles: ['Developer'],
		activities: [],
	},
	{
		company: 'Globant, Mexico City',
		client: 'Clearesult',
		position: 'Team Leader - Web UI Developer',
		duration: { start: 'July 2020', end: 'December 2021' },
		technologies: ['React', 'Magento', 'Material UI', 'Less', 'Webpack'],
		description: [
			'Development of the Eligibility Wizard application, this application allows Clearesult to customize business strategies for its different clients in a personalized and fast way, which minimizes the launch time of Clearesult clients stores.',
			'As leader of the front-end team, my activities are to follow up on the achievement of the stories of my teammates, onboarding, interviews and communication with the client.',
		],
		leader: 'Daniel Rabinovich',
		roles: ['Team Lead', 'Developer'],
		activities: [],
	},
	{
		company: 'Globant, Mexico City',
		client: 'IHS Markit- Santander',
		position: 'Web UI Developer',
		duration: { start: 'June 2019', end: 'June 2020' },
		technologies: ['Svelte.js', 'Sass', 'Chartist.js', 'Google Analytics'],
		description: [
			"Front End development of the Santander International Private Banking system, the system allows Santander's exclusive clients to see all their investment operations, showing Assets and Liabilities, the system is dynamic, interactive and user-friendly, is integrated with Google Analytics to allow Santander to make strategic decisions based on the use of the system.",
		],
		leader: 'Matias Blazquez',
		roles: ['Developer'],
		activities: [],
	},
	{
		company: 'Globant, Mexico City',
		client: 'Citibanamex',
		position: 'Web UI Developer',
		duration: { start: 'March 2017', end: 'June 2019' },
		technologies: [
			'React',
			'Javascript Vanilla',
			'Material UI',
			'Avoka Maestro',
		],
		description: [
			"Development of the Account Opening system, it\u2019s a system that unifies Citibanamex's sales processes, this allows it to sell its products (Credit Cards, Debit Cards, increase credit lines), validating the identity of the client and completing the processes sales in less than 15 minutes, which reduces the waiting time of Citibanamex customers in the branch offices, the system is currently running in all Citibanamex bank branches in Mexico.",
		],
		leader: 'Luis Rey Ortega Dom\u00ednguez',
		roles: ['Developer'],
		activities: [],
	},
	{
		company: 'Sanki Global & Promologistics, Mexico City',
		client: 'Sanki Global',
		position: 'Developer',
		duration: { start: 'August 2016', end: 'March 2017' },
		technologies: [
			'C#',
			'Angular 2',
			'Javascript Vanilla',
			'Chart.js',
			'MSSQL Server',
			'Ionic',
			'Sails',
			'Node.js',
		],
		description: [
			'Development of reporting modules for the Sanki MyConnect system that allows Sanki customers to view statistics and establish sales goals.',
			'Development of the Warehouse mobile application, through which the company monitored and recorded the inputs and outputs of products from the warehouse wirelessly through iPads, improving the productivity of workers within the warehouse.',
		],
		leader: 'Jos\u00e9 Daniel Morales R\u00edos',
		roles: ['Developer'],
		activities: [],
	},
	{
		company: 'ACERTA Computaci\u00f3n Aplicada, Mexico City',
		client: 'SAT (Tax Administration Service)',
		position: 'Developer',
		duration: { start: 'Jul 2015', end: 'August 2016' },
		technologies: ['Java', 'Spring', 'Postgresql', 'Node.js'],
		description: [
			'Development of the SAIE III Identity and Enrollment Accreditation Service, for the SAT(Tax Administration Service), the system allows the capture of biometrics (Fingers, Iris, Photography and Signature) to generate the FIEL (Electronic Signature), the objective is to make the enrollment in less than 10 minutes.',
			'The system generates reports to measure productivity at each enrollment station and was put into production within the time defined in the contract to comply with the provisions of the SAT.',
		],
		leader: 'Miguel Ruiz Velasco Sobrino',
		roles: ['Team Lead', 'Developer'],
		activities: [],
	},
	{
		company: 'Federaci\u00f3n Mexicana de F\u00fatbol, Mexico City',
		client: 'Liga MX and Federaci\u00f3n Mexicana de F\u00fatbol',
		position: 'Senior Web Developer',
		duration: { start: 'August 2010', end: 'February 2015' },
		technologies: [
			'Javascript Vanilla',
			'jQuery',
			'express.js',
			'socket.io',
			'Node.js',
			'Bootstrap',
			'MSSQL Server',
			'C#',
		],
		description: [
			'Analysis, Development and implementation of the SIID system (Integral Sports Information System), FEMEXFUT sports administration system, allowed to automate processes to streamline times and costs for the Federation, communication between the Federation and the Clubs is done through this system, it also allows the administration of the LIGAMX website.',
			'Development of the LIGA MX websites and microsites for the events that the Federation holds every four months. The sites are fully dynamic with real-time updates.',
			'I was in charge of the coordination and logistics of Information Technologies at the Pachuca headquarters during the 2011 Mexico U-17 World Cup, which allowed FIFA to carry out all its operations without setbacks for the event.',
			'As leader of the team, my activities were to support and coordinate Junior programmers in my charge, requirements gathering and communication with product owners.',
		],
		leader: 'Luis Fr\u00edas',
		roles: ['Team Lead', 'Developer'],
		activities: [],
	},
];
